CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, email text UNIQUE NOT NULL, role text NOT NULL CHECK (role IN ('administrador','coordinacion','enfermeria','medicina','direccion','asistente','externo')), active boolean DEFAULT true, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS residents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), first_name text NOT NULL, last_name text NOT NULL, dni text UNIQUE, room text, birth_date date, blood_group text, health_insurance text, allergies text, anticoagulated boolean DEFAULT false, diabetic boolean DEFAULT false, food_preferences text, avoided_foods text, bath_schedule text, status text DEFAULT 'activo', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS resident_contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid NOT NULL REFERENCES residents(id) ON DELETE CASCADE, name text NOT NULL, relationship text NOT NULL, phone text NOT NULL, email text, is_primary boolean DEFAULT false, contact_order int DEFAULT 1, notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS medications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid REFERENCES residents(id), name text NOT NULL, dose text NOT NULL, route text NOT NULL, schedule time[] NOT NULL, active boolean DEFAULT true, indicated_by uuid REFERENCES users(id), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS medication_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), medication_id uuid REFERENCES medications(id), due_at timestamptz NOT NULL, administered_at timestamptz, status text DEFAULT 'pendiente', recorded_by uuid REFERENCES users(id), notes text);
CREATE TABLE IF NOT EXISTS vital_signs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid REFERENCES residents(id), systolic int, diastolic int, heart_rate int, temperature numeric(4,1), oxygen_saturation int, glucose int, recorded_by uuid REFERENCES users(id), recorded_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS care_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid REFERENCES residents(id), type text NOT NULL CHECK(type IN ('catarsis','bano','caida','curacion','vacuna')), details jsonb DEFAULT '{}', status text DEFAULT 'registrado', recorded_by uuid REFERENCES users(id), recorded_at timestamptz DEFAULT now(), evaluated_by uuid REFERENCES users(id), evaluated_at timestamptz);
CREATE TABLE IF NOT EXISTS clinical_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid REFERENCES residents(id), discipline text NOT NULL, note text NOT NULL, include_in_epicrisis boolean DEFAULT false, author_id uuid REFERENCES users(id), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid REFERENCES residents(id), type text NOT NULL, severity text NOT NULL, title text NOT NULL, detail text, target_role text, resolved_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_log (id bigserial PRIMARY KEY, user_id uuid REFERENCES users(id), action text NOT NULL, entity_type text NOT NULL, entity_id uuid, payload jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS clinical_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), resident_id uuid NOT NULL REFERENCES residents(id), file_name text NOT NULL, mime_type text NOT NULL, file_size bigint NOT NULL CHECK(file_size > 0 AND file_size <= 52428800), storage_key text NOT NULL, category text DEFAULT 'otro', uploaded_by uuid REFERENCES users(id), status text DEFAULT 'activo', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS staff_shifts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), shift_name text NOT NULL CHECK(shift_name IN ('Mañana','Tarde','Noche','Personalizado')), starts_at time NOT NULL, ends_at time NOT NULL, valid_from date DEFAULT current_date, valid_until date, assigned_by uuid REFERENCES users(id), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS nurse_resident_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nurse_id uuid NOT NULL REFERENCES users(id), resident_id uuid NOT NULL REFERENCES residents(id), shift_name text NOT NULL, valid_from date DEFAULT current_date, valid_until date, assigned_by uuid REFERENCES users(id), active boolean DEFAULT true, created_at timestamptz DEFAULT now(), UNIQUE(nurse_id,resident_id,shift_name,valid_from));
INSERT INTO users(name,email,role) VALUES ('Valeria Méndez','admin@serena.demo','administrador'),('Dra. Julia Ferrer','medico@serena.demo','medicina'),('Marina López','enfermeria@serena.demo','enfermeria'),('Carlos Benítez','administrativo@serena.demo','administrador') ON CONFLICT DO NOTHING;
INSERT INTO residents(first_name,last_name,dni,room,blood_group,allergies,diabetic,bath_schedule) VALUES ('Elena','Rossi','14403911','12A','A+','Penicilina',true,'Mar y Vie · mañana'),('Manuel','Pereyra','12920487','08B','O+','Sin alergias',false,'Lun y Jue · mañana'),('Ofelia','Suárez','15112880','15A','B-','Látex',false,'Mié y Sáb · tarde'),('Raúl','Domínguez','13776420','06A','A-','Sin alergias',true,'Mar y Vie · tarde') ON CONFLICT DO NOTHING;

-- Ubicación asistencial y firma biométrica (WebAuthn)
ALTER TABLE residents ADD COLUMN IF NOT EXISTS floor smallint CHECK (floor between 1 and 5);
ALTER TABLE residents ADD COLUMN IF NOT EXISTS bed text;
ALTER TABLE staff_shifts ADD COLUMN IF NOT EXISTS floor smallint CHECK (floor between 1 and 5);
CREATE TABLE IF NOT EXISTS webauthn_challenges (email text NOT NULL,purpose text NOT NULL,challenge text NOT NULL,expires_at timestamptz NOT NULL,PRIMARY KEY(email,purpose));
CREATE TABLE IF NOT EXISTS passkey_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,credential_id text UNIQUE NOT NULL,public_key bytea NOT NULL,counter bigint NOT NULL DEFAULT 0,transports text[] DEFAULT '{}',device_type text,backed_up boolean DEFAULT false,professional_name text NOT NULL,license text NOT NULL,created_at timestamptz DEFAULT now(),last_used_at timestamptz);
ALTER TABLE clinical_notes ADD COLUMN IF NOT EXISTS signature_credential_id uuid REFERENCES passkey_credentials(id);
ALTER TABLE clinical_notes ADD COLUMN IF NOT EXISTS signature_verified_at timestamptz;
ALTER TABLE clinical_notes ADD COLUMN IF NOT EXISTS signature_snapshot jsonb;
CREATE INDEX IF NOT EXISTS idx_passkey_user ON passkey_credentials(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_role_unresolved ON alerts(target_role) WHERE resolved_at IS NULL;
UPDATE residents SET floor=CASE room WHEN '12A' THEN 2 WHEN '15A' THEN 3 ELSE 1 END,bed=right(room,1),room=left(room,length(room)-1) WHERE floor IS NULL AND room ~ '^[0-9]+[A-Za-z]$';
