import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, AlertTriangle, Bath, Bell, Check, ChevronDown, ClipboardPlus, FileHeart, HeartPulse, Home, Menu, Pencil, Pill, Plus, Search, Stethoscope, Trash2, Users, X} from 'lucide-react';
import './styles.css';

type Module = 'resumen'|'medicacion'|'controles'|'cuidados'|'residentes'|'hce';
type DemoUser={email:string,password:string,name:string,role:string,initials:string};
const demoUsers:DemoUser[]=[
 {email:'admin@serena.demo',password:'AdminDemo2026!',name:'Valeria Méndez',role:'Administrador',initials:'VM'},
 {email:'medico@serena.demo',password:'MedicoDemo2026!',name:'Dra. Julia Ferrer',role:'Médica',initials:'JF'},
 {email:'enfermeria@serena.demo',password:'EnfermeriaDemo2026!',name:'Marina López',role:'Enfermería',initials:'ML'},
 {email:'administrativo@serena.demo',password:'AdministrativoDemo2026!',name:'Carlos Benítez',role:'Administrativo',initials:'CB'},
];
const people = [
  {name:'Elena Rossi', room:'12A', age:84, initials:'ER', color:'#D9A46F', risk:'Diabetes', insurance:'PAMI · Nº 14-403911-2', contacts:[{name:'Laura Rossi',relation:'Hija',phone:'11 6248-1930',primary:true},{name:'Martín Rossi',relation:'Hijo',phone:'11 4402-8711',primary:false}], meds:['Metformina · 850 mg','Enalapril · 10 mg']},
  {name:'Manuel Pereyra', room:'08B', age:79, initials:'MP', color:'#7FAE9C', risk:'Anticoagulado', insurance:'IOMA · Nº 12-920487', contacts:[{name:'Sofía Pereyra',relation:'Hija',phone:'11 5821-4760',primary:true}], meds:['Apixabán · 5 mg','Losartán · 50 mg']},
  {name:'Ofelia Suárez', room:'15A', age:91, initials:'OS', color:'#A99AC8', risk:'UPP estadio 2', insurance:'PAMI · Nº 15-112880-7', contacts:[{name:'Diego Suárez',relation:'Nieto',phone:'11 3901-2268',primary:true},{name:'Clara Gómez',relation:'Apoderada',phone:'11 6330-9082',primary:false}], meds:['Paracetamol · 500 mg','Omeprazol · 20 mg']},
  {name:'Raúl Domínguez', room:'06A', age:82, initials:'RD', color:'#7EA8C9', risk:'Diabetes', insurance:'OSDE · Plan 210', contacts:[{name:'María Domínguez',relation:'Esposa',phone:'11 4780-5521',primary:true}], meds:['Insulina NPH · 12 UI','Amlodipina · 5 mg']},
];
const nav = [{id:'resumen',label:'Resumen',icon:Home},{id:'medicacion',label:'Medicación',icon:Pill},{id:'controles',label:'Signos vitales',icon:HeartPulse},{id:'cuidados',label:'Cuidados',icon:Bath},{id:'residentes',label:'Residentes',icon:Users},{id:'hce',label:'HCE',icon:FileHeart}] as const;

function Avatar({p}:{p:typeof people[0]}){return <span className="avatar" style={{background:p.color}}>{p.initials}</span>}
function Header({active,setActive,user,onLogout}:{active:Module,setActive:(m:Module)=>void,user:DemoUser,onLogout:()=>void}){
 const [mobileOpen,setMobileOpen]=useState(false);
 const choose=(module:Module)=>{setActive(module);setMobileOpen(false)};
 return <><header><div className="brand"><span className="brandmark">S</span><span>Serena</span><small>Gestión integral</small></div><nav>{nav.map(n=><button className={active===n.id?'active':''} onClick={()=>choose(n.id)} key={n.id}><n.icon size={17}/>{n.label}</button>)}</nav><div className="profile"><button className="icon" aria-label="Buscar"><Search size={20}/></button><button className="icon has-dot" aria-label="Alertas"><Bell size={20}/></button><span className="avatar user">{user.initials}</span><div><b>{user.name}</b><small>{user.role} · Demo</small></div><button className="logout" onClick={onLogout}>Salir</button></div></header><div className="mobilebar"><button onClick={()=>setMobileOpen(!mobileOpen)} aria-label={mobileOpen?'Cerrar menú':'Abrir menú'} aria-expanded={mobileOpen}>{mobileOpen?<X/>:<Menu/>}</button><b>Serena</b><span>{user.role}</span></div>{mobileOpen&&<div className="mobilemenu"><div className="mobileuser"><span className="avatar user">{user.initials}</span><div><b>{user.name}</b><small>{user.role} · Demo</small></div></div>{nav.map(n=><button className={active===n.id?'active':''} onClick={()=>choose(n.id)} key={n.id}><n.icon size={18}/><span>{n.label}</span>{active===n.id&&<Check size={16}/>}</button>)}<button onClick={onLogout}><X size={18}/><span>Cerrar sesión</span></button></div>}</>
}
const TaskCard=({icon:Icon,count,title,detail,tone,onClick}:{icon:any,count:number,title:string,detail:string,tone:string,onClick?:()=>void})=><button className={`task ${tone}`} onClick={onClick}><span className="task-icon"><Icon size={23}/></span><span className="task-copy"><small>{detail}</small><strong>{count}</strong><b>{title}</b></span><span className="arrow">→</span></button>;
function Dashboard({go}:{go:(m:Module)=>void}){
 return <main><section className="welcome"><div><span className="eyebrow">OPERACIÓN / TURNO MAÑANA</span><h1>Panel del turno</h1><p>Miércoles 10 de septiembre · 07:00–15:00 · <b>42 residentes activos</b></p></div><div className="shift"><span className="live"></span><div><small>Estado del turno</small><b>En curso · restan 4 h 18 min</b></div><div className="progress"><i/></div></div></section>
 <section className="section-head"><div><h2>Pendientes operativos</h2><p>Actualizado hace 2 minutos · ordenado por prioridad</p></div><button className="outline"><ClipboardPlus size={18}/> Registrar evento</button></section>
 <div className="tasks"><TaskCard icon={Pill} count={5} title="Dosis pendientes" detail="2 vencidas hace +1 h" tone="red" onClick={()=>go('medicacion')}/><TaskCard icon={HeartPulse} count={3} title="Controles pendientes" detail="1 valor fuera de rango" tone="orange" onClick={()=>go('controles')}/><TaskCard icon={Activity} count={2} title="Catarsis negativas" detail="Sin registro hace +48 h" tone="purple" onClick={()=>go('cuidados')}/><TaskCard icon={AlertTriangle} count={1} title="Caída sin evaluar" detail="Registrada hoy, 08:42" tone="blue" onClick={()=>go('cuidados')}/></div>
 <div className="dashboard-grid"><section className="panel medication"><div className="panel-title"><div><span className="mini pill"><Pill size={16}/></span><h3>Próxima ronda</h3><span className="tag">10:00</span></div><button onClick={()=>go('medicacion')}>Ver planilla completa →</button></div>{people.slice(0,3).map((p,i)=><div className="row" key={p.name}><Avatar p={p}/><div className="person"><b>{p.name}</b><small>Hab. {p.room} · {p.age} años</small></div><div className="drug"><b>{p.meds[0]}</b><small>{i===1?'Vía gastrostomía':'Vía oral'}</small></div><button className={i===0?'done':'confirm'}>{i===0?<><Check size={17}/>Administrada 09:56</>:<>Confirmar dosis</>}</button></div>)}</section>
 <aside className="panel clinical"><div className="panel-title"><div><span className="mini heart"><HeartPulse size={16}/></span><h3>Situación clínica</h3></div><button>Ver todas →</button></div><div className="clinical-item danger"><div><b>TA fuera de rango</b><small>Elena Rossi · Hab. 12A</small></div><strong>168/104</strong><span>mmHg</span></div><div className="clinical-item"><div><b>Curación pendiente</b><small>Ofelia Suárez · Sacro</small></div><span className="status">Hoy</span></div><div className="clinical-item"><div><b>Nueva indicación</b><small>Raúl Domínguez · Dra. Ferrer</small></div><span className="status mint">Revisar</span></div></aside></div>
 <section className="quick"><h3>Accesos operativos</h3><p>Registros frecuentes del turno</p><div><button onClick={()=>go('controles')}><HeartPulse/>Signos vitales</button><button onClick={()=>go('cuidados')}><Activity/>Registrar catarsis</button><button onClick={()=>go('cuidados')}><Bath/>Registrar baño</button><button onClick={()=>go('cuidados')}><AlertTriangle/>Informar caída</button><button><Plus/>Otra acción</button></div></section></main>
}
function Medication(){const [done,setDone]=useState<string[]>(['Elena Rossi']); return <main><PageTitle eyebrow="PLANILLA GENERAL · TURNO MAÑANA" title="Medicación" text="Administración por horario, con registro automático de usuario y hora."/><div className="toolbar"><div className="seg"><button>07:00</button><button className="sel">10:00</button><button>12:00</button><button>14:00</button></div><label><Search size={17}/><input placeholder="Buscar residente o medicamento"/></label></div><section className="panel medtable"><div className="tablehead"><span>Residente</span><span>Indicación</span><span>Vía</span><span>Estado</span></div>{people.map((p,i)=><div className="medrow" key={p.name}><div><Avatar p={p}/><p><b>{p.name}</b><small>Hab. {p.room}</small></p></div><div><b>{p.meds[0]}</b><small>Indicación vigente · Dra. Ferrer</small></div><span className="route">{i===1?'Gastrostomía':'Oral'}</span><button onClick={()=>setDone([...done,p.name])} className={done.includes(p.name)?'done':'confirm'}>{done.includes(p.name)?<><Check size={17}/>Administrada</>:i===2?<><AlertTriangle size={16}/>Vencida · confirmar</>:'Confirmar dosis'}</button></div>)}</section></main>}
function Controls(){const [saved,setSaved]=useState(false); return <main><PageTitle eyebrow="PLANILLA GENERAL · TURNO MAÑANA" title="Signos vitales" text="Carga rápida. Los valores de alerta se detectan al instante."/><section className="panel vitals"><div className="tablehead six"><span>Residente</span><span>TA</span><span>FC</span><span>Temp.</span><span>Sat. O₂</span><span>HGT</span></div>{people.map((p,i)=><div className="vitalrow" key={p.name}><div><Avatar p={p}/><p><b>{p.name}</b><small>Hab. {p.room}</small></p></div><input className={i===0?'warn':''} defaultValue={i===0?'168/104':''} placeholder="— / —"/><input defaultValue={i===0?'82':''} placeholder="—"/><input defaultValue={i===0?'36.7':''} placeholder="—"/><input defaultValue={i===0?'96':''} placeholder="—"/><input placeholder={p.risk==='Diabetes'?'mg/dl':'Opcional'}/></div>)}</section><div className="savebar"><span>{saved?'✓ Planilla guardada por Marina López':'Los cambios quedarán asociados a tu usuario'}</span><button onClick={()=>setSaved(true)}>Guardar controles</button></div></main>}
function Residents(){
 const [records,setRecords]=useState(people); const [selected,setSelected]=useState(people[0]); const [editing,setEditing]=useState(false);
 const saveResident=(data:Partial<typeof selected>)=>{const next={...selected,...data};setRecords(records.map(p=>p.name===selected.name?next:p));setSelected(next);setEditing(false)};
 const deactivate=()=>{if(!window.confirm(`¿Dar de baja a ${selected.name}? Su historia clínica se conservará.`))return;const remaining=records.filter(p=>p.name!==selected.name);setRecords(remaining);if(remaining[0])setSelected(remaining[0])};
 const deleteContact=(name:string)=>{if(!window.confirm(`¿Eliminar el contacto ${name}?`))return;const next={...selected,contacts:selected.contacts.filter(c=>c.name!==name)};setRecords(records.map(p=>p.name===selected.name?next:p));setSelected(next)};
 return <main><PageTitle eyebrow="PADRÓN ACTIVO" title="Residentes" text={`${records.length} residentes visibles · fichas clínicas y administrativas conectadas.`}/><div className="residents-layout"><section className="panel resident-list"><label><Search size={17}/><input placeholder="Buscar por nombre, DNI o habitación"/></label>{records.map(p=><button onClick={()=>setSelected(p)} className={selected.name===p.name?'selected':''} key={p.name}><Avatar p={p}/><span><b>{p.name}</b><small>Hab. {p.room} · {p.age} años</small></span><em>{p.risk}</em></button>)}</section><section className="profile-card"><div className="record-actions"><button onClick={()=>setEditing(true)}><Pencil size={14}/> Editar datos</button><button className="danger-action" onClick={deactivate}><Trash2 size={14}/> Dar de baja</button></div><div className="profile-top"><Avatar p={selected}/><div><small>HABITACIÓN {selected.room}</small><h2>{selected.name}</h2><p>{selected.age} años · DNI 14.403.911</p></div><button>Ver HCE completa</button></div><div className="facts resident-facts"><article><small>Obra social / cobertura</small><b>{selected.insurance}</b></article><article><small>Grupo sanguíneo</small><b>A positivo</b></article><article><small>Alergias</small><b>Penicilina</b></article><article><small>Condición relevante</small><b>{selected.risk}</b></article></div><div className="profile-columns"><section className="family"><div className="subhead"><div><h3>Contactos familiares</h3><small>Orden de contacto ante una emergencia</small></div><button><Plus size={14}/> Agregar</button></div>{selected.contacts.map((contact,index)=><article key={contact.name}><span className="contact-order">{index+1}</span><div><b>{contact.name}</b><small>{contact.relation}{contact.primary?' · Contacto principal':''}</small></div><a href={`tel:${contact.phone.replaceAll(' ','')}`}>{contact.phone}</a><div className="inline-actions"><button aria-label={`Editar ${contact.name}`}><Pencil size={13}/></button><button aria-label={`Eliminar ${contact.name}`} onClick={()=>deleteContact(contact.name)}><Trash2 size={13}/></button></div></article>)}</section><section><h3>Actividad de hoy</h3><div className="timeline"><p><i className="green"/><b>09:56</b> Medicación administrada <small>por Marina López</small></p><p><i className="blue"/><b>09:12</b> Signos vitales registrados <small>TA 128/78 · Sat. 96%</small></p><p><i className="purple"/><b>08:15</b> Desayuno y catarsis <small>por Ana Torres</small></p></div></section></div></section></div>{editing&&<ResidentEditor resident={selected} onClose={()=>setEditing(false)} onSave={saveResident}/>}</main>
}
function ResidentEditor({resident,onClose,onSave}:{resident:typeof people[0],onClose:()=>void,onSave:(data:Partial<typeof resident>)=>void}){const [form,setForm]=useState({name:resident.name,room:resident.room,age:String(resident.age),insurance:resident.insurance,risk:resident.risk});const change=(key:keyof typeof form,value:string)=>setForm({...form,[key]:value});return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="editor" onSubmit={e=>{e.preventDefault();onSave({...form,age:Number(form.age),initials:form.name.split(' ').map(n=>n[0]).join('').slice(0,2).toUpperCase()})}}><div className="editor-head"><div><span className="eyebrow">DATOS DEL RESIDENTE</span><h2>Editar ficha</h2></div><button type="button" onClick={onClose} aria-label="Cerrar"><X/></button></div><div className="form-grid"><label>Nombre completo<input value={form.name} onChange={e=>change('name',e.target.value)} required/></label><label>Habitación<input value={form.room} onChange={e=>change('room',e.target.value)} required/></label><label>Edad<input type="number" value={form.age} onChange={e=>change('age',e.target.value)} required/></label><label>Condición relevante<input value={form.risk} onChange={e=>change('risk',e.target.value)}/></label><label className="wide">Obra social / Nº de afiliado<input value={form.insurance} onChange={e=>change('insurance',e.target.value)} required/></label></div><div className="editor-footer"><small>La modificación quedará registrada a nombre de Marina López.</small><button type="button" onClick={onClose}>Cancelar</button><button className="primary" type="submit">Guardar cambios</button></div></form></div>}
function Placeholder({type}:{type:'cuidados'|'hce'}){return <main><PageTitle eyebrow={type==='hce'?'HISTORIA CLÍNICA ELECTRÓNICA':'REGISTROS DEL TURNO'} title={type==='hce'?'Historia clínica':'Cuidados diarios'} text={type==='hce'?'Evoluciones conectadas de medicina, enfermería y otros profesionales.':'Catarsis, baños, caídas y curaciones en un mismo flujo.'}/><div className="modulecards">{(type==='hce'?[[Stethoscope,'Evoluciones médicas','Etiquetado para epicrisis'],[FileHeart,'Valoración integral','Pfeiffer, MMSE, MoCA, Katz y Norton'],[Users,'Equipo interdisciplinario','Nutrición, kinesiología, psicología y más']]:[[Activity,'Catarsis','2 registros requieren atención'],[Bath,'Baños','8 programados en este turno'],[AlertTriangle,'Caídas','1 pendiente de evaluación médica']]).map(([I,t,d]:any)=><button><I/><span><b>{t}</b><small>{d}</small></span>→</button>)}</div></main>}
function PageTitle({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <section className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div><button className="primary"><Plus size={18}/> Nuevo registro</button></section>}
function AlertDock(){const [open,setOpen]=useState(false); return <div className={`alertdock ${open?'open':''}`}><button className="alerttab" onClick={()=>setOpen(!open)}><span><Bell size={18}/><b>6 alertas activas</b></span><small>2 requieren atención inmediata</small><ChevronDown size={18}/></button>{open&&<div className="alertcontent"><button><span className="dot red"/><div><b>Medicación vencida</b><small>Ofelia Suárez · Paracetamol · hace 1 h 22 min</small></div>→</button><button><span className="dot orange"/><div><b>TA fuera de rango</b><small>Elena Rossi · 168/104 mmHg</small></div>→</button><button onClick={()=>setOpen(false)} className="close"><X/></button></div>}</div>}
function Login({onLogin}:{onLogin:(user:DemoUser)=>void}){const [email,setEmail]=useState('admin@serena.demo');const [password,setPassword]=useState('AdminDemo2026!');const [error,setError]=useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();const user=demoUsers.find(u=>u.email===email&&u.password===password);if(!user){setError('Usuario o contraseña incorrectos');return}onLogin(user)};return <div className="login-page"><section className="login-brand"><span className="brandmark">S</span><h1>Serena</h1><p>Gestión integral para residencias</p><small>ENTORNO DE DEMOSTRACIÓN · DATOS FICTICIOS</small></section><form className="login-card" onSubmit={submit}><span className="eyebrow">ACCESO AL SISTEMA</span><h2>Iniciar sesión</h2><p>Ingresá con uno de los perfiles de demostración.</p><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<div className="login-error">{error}</div>}<button type="submit">Ingresar</button><div className="demo-access"><b>Accesos rápidos</b>{demoUsers.map(u=><button type="button" key={u.email} onClick={()=>{setEmail(u.email);setPassword(u.password)}}><span>{u.initials}</span><div>{u.role}<small>{u.email}</small></div></button>)}</div></form></div>}
function PrivacyNotice({onClose}:{onClose:()=>void}){return <div className="privacy-backdrop"><section className="privacy-notice" role="dialog" aria-modal="true" aria-labelledby="privacy-title"><div className="privacy-head"><span>AVISO DE PRIVACIDAD Y CONFIDENCIALIDAD</span><button onClick={onClose} aria-label="Cerrar aviso"><X/></button></div><div className="privacy-body"><h2 id="privacy-title">Protección de datos personales</h2><p>Este sistema puede contener datos personales y datos de salud, considerados sensibles por la Ley argentina 25.326. El acceso está limitado a tareas autorizadas y toda consulta o modificación debe responder a una finalidad asistencial o administrativa legítima.</p><ul><li>No compartas información por canales no autorizados.</li><li>No descargues, fotografíes ni copies datos sin justificación.</li><li>Cerrá la sesión al terminar y reportá accesos o incidentes sospechosos.</li><li>Esta demostración utiliza exclusivamente información ficticia.</li></ul><p className="privacy-foot">Al continuar declarás haber leído el aviso. El cierre queda registrado para esta sesión de demostración.</p></div><button className="privacy-accept" onClick={onClose}>Entendido, continuar</button></section></div>}
function App(){const [active,setActive]=useState<Module>('resumen');const [user,setUser]=useState<DemoUser|null>(null);const [privacyOpen,setPrivacyOpen]=useState(false);const content=useMemo(()=>active==='resumen'?<Dashboard go={setActive}/>:active==='medicacion'?<Medication/>:active==='controles'?<Controls/>:active==='residentes'?<Residents/>:<Placeholder type={active}/>,[active]);if(!user)return <Login onLogin={u=>{setUser(u);setPrivacyOpen(true)}}/>;return <><Header active={active} setActive={setActive} user={user} onLogout={()=>{setUser(null);setActive('resumen')}}/>{content}<AlertDock/>{privacyOpen&&<PrivacyNotice onClose={()=>setPrivacyOpen(false)}/>}</>}
createRoot(document.getElementById('root')!).render(<App/>);
